[package]
name = "noq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = { version = "*", optional = true }

[features]
new_repl = ["dep:termion"]